query restaurantsPageQuery($input: RestaurantsInput!) {
  allCategories {
    ok
    error
    categories {
      ...CategoryParts
    }
  }
  restaurants(input: $input) {
    ok
    error
    totalPages
    totalResults
    results {
      ...RestaurantParts
    }
  }
}
