query AdminGetRestaurants($page: Int, $q: String, $take: Int) {
  adminGetRestaurants(page: $page, q: $q, take: $take) {
    error
    hasNext
    hasPrevious
    matchedCount
    ok
    pageCount
    data {
      address
      categories {
        restaurantCount
        coverImageUrl
        createdAt
        id
        name
        slug
        updatedAt
      }
      coverImageUrls
      createdAt
      id
      isPromoted
      name
      promotedUntil
      updatedAt
      vendors {
        ...UserParts
      }
    }
  }
}
