query AdminGetUsers($role: UserRole, $q: String, $take: Int, $page: Int) {
  adminGetUsers(role: $role, q: $q, take: $take, page: $page) {
    error
    hasNext
    hasPrevious
    matchedCount
    ok
    pageCount
    data {
      createdAt
      firstName
      lastName
      email
      id
      roles
      updatedAt
      isVerified
      photoURL
    }
  }
}
