query category($page: Int, $slug: String!) {
  category(page: $page, slug: $slug) {
    ok
    error
    pageCount
    hasPrevious
    hasNext
    matchedCount
    category {
      id
      name
      slug
      coverImageUrl
      restaurantCount
    }
    restaurants {
      ...RestaurantParts
    }
    category {
      ...CategoryParts
    }
  }
}
