query category($page: Int, $slug: String!) {
  category(page: $page, slug: $slug) {
    ok
    error
    totalPages
    totalResults
    restaurants {
      ...RestaurantParts
    }
    category {
      ...CategoryParts
    }
  }
}
