query Categories($page: Int, $q: String, $take: Int) {
  categories(page: $page, q: $q, take: $take) {
    categories {
      coverImageUrl
      createdAt
      id
      name
      restaurantCount
      slug
      updatedAt
    }
    error
    hasNext
    hasPrevious
    matchedCount
    ok
    pageCount
  }
}
