query myRestaurant($input: MyRestaurantInput!) {
  myRestaurant(input: $input) {
    ok
    error
    restaurant {
      ...RestaurantParts
      menu {
        ...DishParts
      }
      orders {
        ...OrderParts
      }
    }
  }
}
