query RestaurantById($id: Int!) {
  restaurant(id: $id){
    error
    ok
    restaurant {
      address
      categories {
        coverImageUrl
        createdAt
        id
        name
        restaurantCount
        slug
        updatedAt
      }
      coverImageUrls
      createdAt
      id
      isPromoted
      logoImageUrl
      menu {
        createdAt
        description
        id
        name
        options {
          choices {
            extra
            name
          }
          extra
          name
        }
        photo
        price
        updatedAt
      }
      name
      promotedUntil
      updatedAt
    }
  }
}
