query searchRestaurant($page: Int, $take: Int, $query: String) {
  searchRestaurant(page: $page, query: $query, take: $take) {
    ok
    error
    hasNext
    matchedCount
    hasPrevious
    pageCount
    restaurants {
      ...RestaurantParts
    }
  }
}
