fragment FullOrderParts on Order {
  id
  status
  total
  driver {
    email
  }
  customer {
    email
  }
  restaurant {
    name
  }
}

fragment RestaurantParts on Restaurant {
  id
  name
  coverImg
  category {
    name
    coverImageUrl
  }
  address
  isPromoted
}

fragment CategoryParts on Category {
  id
  name
  coverImageUrl
  slug
  restaurantCount
}

fragment DishParts on Dish {
  id
  name
  price
  photo
  description
  options {
    name
    extra
    choices {
      name
      extra
    }
  }
}

fragment OrderParts on Order {
  id
  createdAt
  total
}
